### ISSUE TITLE
Needs updating to Ember 3.x, ember-cli-babel 6.x

### ISSUE THREAD

**Issue by buzzware** [ibroadfo/ember-cli-deploy-firebase#5]
This was holding my Ember 3.1 app back to ember-cli-babel 5.x. When I removed ember-cli-deploy-firebase-pack to use @econlab/ember-cli-deploy-firebase I got ember-cli-babel 6.x, but then I got a build error :

$ ember deploy production
cleaning up...
Deploying [🚀 ] 100% [plugin: firebase -> upload]
- Starting deploy process...
- There was an error during deployment:
- TypeError: Cannot read property 'has' of undefined
- TypeError: Cannot read property 'has' of undefined
    at /Users/gary/repos/2018/ASDDriver/browser/node_modules/firebase-tools/lib/filterTargets.js:8:27
    at Array.filter (<anonymous>)
    at module.exports (/Users/gary/repos/2018/ASDDriver/browser/node_modules/firebase-tools/lib/filterTargets.js:7:30)
    at Command._action (/Users/gary/repos/2018/ASDDriver/browser/node_modules/firebase-tools/commands/deploy.js:52:19)
    at /Users/gary/repos/2018/ASDDriver/browser/node_modules/firebase-tools/lib/command.js:200:29
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)

Should we use "firebase deploy" instead ?

**Comment by alexparker** [comment]
@buzzware did you figure out a work-around or solution? I have run into this now too, and was curious

**Comment by buzzware** [comment]
@alexparker No, I just use "ember build -e production" then "firebase deploy" and not this or ember deploy at all, which is why I posted https://github.com/ibroadfo/ember-cli-deploy-firebase/issues/6

**Comment by mileszim** [comment]
@buzzware @alexparker I'd be happy to do a full ember-cli upgrade and fix errors for the one at econlab tomorrow or so, I'll keep you posted.
