### ISSUE TITLE
Failing to make deploy

### ISSUE THREAD

**Issue by ollar** [ibroadfo/ember-cli-deploy-firebase#7]
Running command 'ember deploy production' I get error:

```
HTTP Error: 410, Unknown Error
{"context":{"body":{"error":{"message":"Unknown Error"}},"response":{"statusCode":410,"headers":{"server":"nginx","date":"Thu, 25 Oct 2018 14:43:52 GMT","content-type":"application/json; charset=utf-8","content-length":"240","connection":"close","access-control-allow-origin":"*","access-control-allow-methods":"GET, PUT, POST, DELETE, OPTIONS","strict-transport-security":"max-age=31556926; includeSubDomains; preload"},"request":{"uri":{"protocol":"https:","slashes":true,"auth":null,"host":"deploy.firebase.com","port":443,"hostname":"deploy.firebase.com","hash":null,"search":"?fileCount=48&message=","query":"fileCount=48&message=","pathname":"/v1/hosting/***/uploads/-LPffazPlggI6L9iYOjD","path":"/v1/hosting/***/uploads/-LPffazPlggI6L9iYOjD?fileCount=48&message=","href":"https://deploy.firebase.com/v1/hosting/***/uploads/-LPffazPlggI6L9iYOjD?fileCount=48&message="},"method":"PUT"}}},"exit":1}
```

```
- something bad happened oh no
- FirebaseError: HTTP Error: 410, Unknown Error
- Error
    at new FirebaseError (/home/ollar/Documents/dev/***/node_modules/firebase-tools/lib/error.js:16:16)
    at module.exports (/home/ollar/Documents/dev/***/node_modules/firebase-tools/lib/responseToError.js:38:10)
    at Request._callback (/home/ollar/Documents/dev/***/node_modules/firebase-tools/lib/api.js:47:25)
    at Request.self.callback (/home/ollar/Documents/dev/***/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.EventEmitter.emit (domain.js:442:20)
    at Request.<anonymous> (/home/ollar/Documents/dev/***/node_modules/request/request.js:1157:10)
    at Request.emit (events.js:182:13)
    at Request.EventEmitter.emit (domain.js:442:20)
    at IncomingMessage.<anonymous> (/home/ollar/Documents/dev/***/node_modules/request/request.js:1079:12)
```
Can anyone help me with this?

Thanks.

**Comment by ollar** [comment]
addon version - 2.14
error appeared on October 24

**Comment by bakertim** [comment]
@ollar I had the exact same issue today. Make sure you are running the latest version of `firebase-tools` by running `npm install -g firebase-tools`. You should be using version >=5.1.1.

https://stackoverflow.com/questions/52993854/firebase-deploy-only-hosting-gives-error-http-error-410-unknown-error.

**Comment by ollar** [comment]
@angrybear11 Thanks! I've found the reason too. I have already installed latest firebase-tools globally but the plugin uses local firebase-tools installed as dependency. So your solution did not suit me, unfortunately. 

I've created a pull request where dependency was fixed #8 , this solved the problem for me. And it also removed the babel deprecation warning :)

**Comment by mminkoff** [comment]
I also had to logout of firebase on the command line `firebase logout` and log back in `firebase login` to get it to work.

**Comment by jernejc** [comment]
My Travis-CI deploy is failing for the same reason. The plugin has a dependancy to "firebase-tools": "^3.0.6", can we update this ? 

Also "ember-cli-babel": "^5.1.7" is deprecated as well. Can we just update those two package to the latest versions?

**Comment by esnilara** [comment]
I can see there's an opened pull request already. In the meantime, with Yarn you could use [selective dependency resolutions](https://yarnpkg.com/en/docs/selective-version-resolutions) and override the dependency version of `firebase-tools`. Not sure if npm supports this feature as well.

Include this in your `package.json`.

```javascript
 "resolutions": {
    "ember-cli-deploy-firebase-pack/ember-cli-deploy-firebase/firebase-tools": "5.1.1"
  }
```

Then...

```
rm yarn.lock
yarn cache clean
yarn install
```

After this, in your `yarn.lock` will list only a single package for firebase-tools 5.1.1 with a reference to the version that the addon needs. 

```
firebase-tools@5.1.1, firebase-tools@^3.0.6:
  version "5.1.1"
  resolved "https://registry.yarnpkg.com/firebase-tools/-/firebase-tools-5.1.1.tgz#0e693c6197bdc4562fd3040d7bbb7e23b5dc415c"
  dependencies:
```

This indicates that `ember deploy` will use the only available firebase-tools 5.1.1.

Hope this helps!
